import { Inter } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import { Head } from "next/document";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {},
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/img/assets/favicon_io/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/img/assets/favicon_io/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/img/assets/favicon_io/favicon-16x16.png"
        />
        <link rel="manifest" href="/img/assets/favicon_io/site.webmanifest" />
      </head>

      <body className={`${inter} antialiased`} data-theme="light">
        {children}
      </body>
    </html>
  );
}
